apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hanko
  namespace: {{ .Release.Namespace }}
  labels:
    app: hanko
spec:
  replicas: {{ .Values.replicas | default 2 }}
  selector:
    matchLabels:
      app: hanko
  template:
    metadata:
      labels:
        app: hanko
    spec:
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: hanko
          image: {{ .Values.image.repository }}-backend:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{ toYaml .Values.containerSecurityContext | nindent 12 }}
          env:
            - name: PASSWORD_ENABLED
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: tls-certs
              mountPath: /etc/tls
              readOnly: true
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 8000
              name: public
            - containerPort: 8001
              name: admin
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
        - name: tls-certs
          secret:
            secretName: {{ .Release.Name }}-tls
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: hanko
                topologyKey: kubernetes.io/hostname