{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-hanko
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-hanko
                port:
                  number: 8000
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-hanko
                port:
                  number: 8001
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Release.Name }}-tls
  {{- end }}
{{- end }}