apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hanko
  namespace: {{ .Release.Namespace }}
  labels:
    app: hanko
spec:
  ports:
    - name: public
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
  selector:
    app: hanko