apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suricata-logs
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{storage_class}}
  resources:
    requests:
      storage: {{log_storage_size}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suricata-rules
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{storage_class}}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suricata-config
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{storage_class}}
  resources:
    requests:
      storage: 1Gi