apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcapan-pvc
  namespace: pcapan-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcapan-web
  namespace: pcapan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcapan-web
  template:
    metadata:
      labels:
        app: pcapan-web
    spec:
      containers:
      - name: pcapan-web
        image: pcapan-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: JWT_SECRET
          value: "secret"
        volumeMounts:
        - name: pcaps
          mountPath: /pcaps
      volumes:
      - name: pcaps
        persistentVolumeClaim:
          claimName: pcapan-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pcapan-web
  namespace: pcapan-ns
spec:
  selector:
    app: pcapan-web
  ports:
  - protocol: TCP
    port: 443
    targetPort: 3000
  type: ClusterIP