---
services:
  gotestwaf:
    image: gotestwaf
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - {{ output_dir }}:/app/reports
    command: ["/app/gotestwaf", "--url={{ item }}", "--noEmailReport"]
    deploy:
      mode: replicated
      replicas: {{ parallel }}
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "gotestwaf", "|", "grep", "-v", "grep"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s