apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defguard-db-pvc
  namespace: defguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard