[source::...ta-cribl-logging-for-splunk*.log*]
sourcetype = tacriblloggingforsplunk:log

[source::...ta_cribl_logging_for_splunk*.log*]
sourcetype = tacriblloggingforsplunk:log

[access]
AUTO_KV_JSON = 0
INDEXED_EXTRACTIONS = json
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = true
SHOULD_LINEMERGE = 0
TIMESTAMP_FIELDS = time
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3NZ
TIME_PREFIX = ^
category = Splunk App Add-on Builder
pulldown_type = 1

[notifications]
AUTO_KV_JSON = 0
INDEXED_EXTRACTIONS = json
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = 1
SHOULD_LINEMERGE = 0
TIMESTAMP_FIELDS = time
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3NZ
TIME_PREFIX = ^
category = Splunk App Add-on Builder
pulldown_type = 1

[cribl:log]
AUTO_KV_JSON = 0
INDEXED_EXTRACTIONS = json
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = 1
SHOULD_LINEMERGE = 0
TIMESTAMP_FIELDS = time
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3NZ
TIME_PREFIX = ^
category = Splunk App Add-on Builder
pulldown_type = 1

[audit]
AUTO_KV_JSON = 0
INDEXED_EXTRACTIONS = json
LINE_BREAKER = ([\r\n]+)
NO_BINARY_CHECK = 1
SHOULD_LINEMERGE = 0
TIMESTAMP_FIELDS = time
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3NZ
TIME_PREFIX = ^
category = Splunk App Add-on Builder
pulldown_type = 1

