
[admin:TA_cribl_logging_for_splunk]
match = /
members = TA_cribl_logging_for_splunk_account, TA_cribl_logging_for_splunk_settings, TA_cribl_logging_for_splunk_cribl_input

[admin_external:TA_cribl_logging_for_splunk_account]
handlertype = python
python.version = python3
handlerfile = TA_cribl_logging_for_splunk_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_cribl_logging_for_splunk_settings]
handlertype = python
python.version = python3
handlerfile = TA_cribl_logging_for_splunk_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_cribl_logging_for_splunk_cribl_input]
handlertype = python
python.version = python3
handlerfile = TA_cribl_logging_for_splunk_rh_cribl_input.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
