
[expose:TA_cribl_logging_for_splunk_account]
pattern = TA_cribl_logging_for_splunk_account
methods = POST, GET

[expose:TA_cribl_logging_for_splunk_account_specified]
pattern = TA_cribl_logging_for_splunk_account/*
methods = POST, GET, DELETE

[expose:TA_cribl_logging_for_splunk_settings]
pattern = TA_cribl_logging_for_splunk_settings
methods = POST, GET

[expose:TA_cribl_logging_for_splunk_settings_specified]
pattern = TA_cribl_logging_for_splunk_settings/*
methods = POST, GET, DELETE

[expose:TA_cribl_logging_for_splunk_cribl_input]
pattern = TA_cribl_logging_for_splunk_cribl_input
methods = POST, GET

[expose:TA_cribl_logging_for_splunk_cribl_input_specified]
pattern = TA_cribl_logging_for_splunk_cribl_input/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
