HTTP/1.1 403 Forbidden
Cache-Control: no-cache
Connection: close
Content-Type: application/json

{ "errors" : [ { "status" : "403", "title" : "Forbidden", "detail" : "The HTTP 403 Forbidden error code means that a web server understands a request but denies access to a resource. This error can occur when a user doesn't have the proper permissions or authentication credentials." } ] }