HTTP/1.1 502 Bad Gateway
Cache-Control: no-cache
Connection: close
Content-Type: application/json

{ "errors" : [ { "status" : "502", "title" : "Bad Gateway", "detail" : "The HTTP 502 error code, also known as a bad gateway error, indicates that a server received an invalid response from another server. This can happen when a server is acting as a proxy or gateway." } ] }