HTTP/1.1 408 Request Timeout
Cache-Control: no-cache
Connection: close
Content-Type: application/json

{ "errors" : [ { "status" : "408", "title" : "Request Timeout", "detail" : "The HTTP 408 error, also known as the Request Timeout error, indicates that a server did not respond to a request in time." } ] }