HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Connection: close
Content-Type: application/json

{ "errors" : [ { "status" : "500", "title" : "Internal Server Error", "detail" : "The HTTP 500 error code, also known as an internal server error, indicates that the server was unable to fulfill a request due to an unexpected issue. This error is a server-side issue." } ] }