[ req ]
distinguished_name = req_distinguished_name
req_extensions = req_ext
default_md = sha384
prompt = no

[ req_distinguished_name ]
countryName = US
stateOrProvinceName = TN
localityName = SM
organizationName = Umbrella
organizationalUnitName = Infil
commonName = splunkenterprise.io

[ req_ext ]
subjectAltName = @alt_names
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature
# clientAuth required by kvstore/mongod since Splunk 9.4
# https://splunk.my.site.com/customer/s/article/Certificate-issue-when-Upgrading-to-Splu
extendedKeyUsage = serverAuth, clientAuth

[alt_names]
DNS.1 = splunkenterprise.io
DNS.2 = splunkenterprise
IP.1 =