# fluentd/Dockerfile

FROM fluent/fluentd:v1.18.0-debian-amd64-1.0
USER root
RUN ["fluent-gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.4.3"]
RUN ["fluent-gem", "install", "fluent-plugin-cloudwatch", "--no-document", "--version", "2.1.1"]
RUN ["fluent-gem", "install", "fluent-plugin-grok-parser", "--no-document", "--version", "2.6.2"]
USER fluent
