[launcher]
version = 8.0.0
description = This Add-On collects data from Tenable platform and indexes it in Splunk.
author = Tenable Inc.

[id]
version = 8.0.0
name = TA-tenable

[install]
build = 1742537910
is_configured = false
state = enabled

[package]
id = TA-tenable
check_for_updates = true

[ui]
label = Tenable Add-On for Splunk
is_visible = true

[triggers]
reload.ta_tenable_settings = simple
reload.ta_tenable_account = simple
