[vulnerabilities]
search = (sourcetype="tenable:sc:vuln" OR sourcetype="tenable:sc:mobile:vuln" OR sourcetype="tenable:io:vuln" OR sourcetype="tenable:ot:vuln" OR sourcetype="tenable:was:vuln")

[tenable_action]
search = (sourcetype="tenable:sc:vuln_summary:ar" OR sourcetype="tenable:sc:machinescan:ar"  OR sourcetype="tenable:sc:remedscan:ar" OR sourcetype="tenable:io:vuln_summary:ar" OR sourcetype="tenable:io:scan:ar")

[alerts]
search = (sourcetype="tenable:nnm:vuln" AND data_model="alerts" AND data_set="Alerts")

[network_traffic]
search = (sourcetype="tenable:nnm:vuln" AND data_model="network_traffic" AND data_set="All_Traffic")

[alsid_ioe_security_alert]
search = (index=* sourcetype="tenable:ad:alerts" alsid_internal_mtype=0)

[alsid_trailflow_event]
search = (index=* sourcetype="tenable:ad:alerts" alsid_internal_mtype=1)

[alsid_ioa_security_alert]
search = (index=* sourcetype="tenable:ad:alerts" alsid_internal_mtype=2)

[assets]
search = index=* sourcetype="tenable:ot:assets"

[plugins]
search = index=* sourcetype="tenable:ot:plugin"

[io_compliances]
search = index=* sourcetype="tenable:io:compliance"

[asm_assets]
search = index=* sourcetype="tenable:asm:assets"
