
[admin:TA_tenable]
match = /
members = TA_tenable_account, TA_tenable_settings, TA_tenable_tenable_was, TA_tenable_tenable_io, TA_tenable_tenable_securitycenter, TA_tenable_tenable_securitycenter_mobile, TA_tenable_tenable_ot_security_icp, TA_tenable_tenable_io_compliance, TA_tenable_tenable_io_audit_logs, TA_tenable_tenable_asm

[admin_external:TA_tenable_account]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_tenable_settings]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_tenable_tenable_was]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_tenable_was.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_tenable_tenable_io]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_tenable_io.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_tenable_tenable_securitycenter]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_tenable_securitycenter.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_tenable_tenable_securitycenter_mobile]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_tenable_securitycenter_mobile.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_tenable_tenable_ot_security_icp]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_tenable_ot_security_icp.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_tenable_tenable_io_compliance]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_tenable_io_compliance.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_tenable_tenable_io_audit_logs]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_tenable_io_audit_logs.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_tenable_tenable_asm]
handlertype = python
python.version = python3
handlerfile = TA_tenable_rh_tenable_asm.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
