[eventtype=vulnerabilities]
report = enabled
vulnerability = enabled

[eventtype=tenable_action]
modaction_result = enabled

[eventtype=alerts]
alert = enabled

[eventtype=network_traffic]
network = enabled
communicate = enabled

[eventtype=alsid_ioe_security_alert]
alert = enabled

[eventtype=alsid_trailflow_event]
alert = enabled

[eventtype=alsid_ioa_security_alert]
alert = enabled

[eventtype=assets]
inventory = enabled
network = enabled
os = enabled
ot_asset = enabled

[eventtype=plugins]
report = enabled
vulnerability = enabled

[eventtype=io_compliances]
inventory = enabled
network = enabled
os = enabled

[eventtype=asm_assets]
inventory = enabled
network = enabled