<#
.SYNOPSIS
    IIS Hardening Script for Modern Security Best Practices
    Applies hardening settings based on config.ini.

.DESCRIPTION
    This script reads recommended configurations from config.ini (generated by Audit-IIS.ps1)
    and applies them globally and per-site. This script first runs Backup-IIS-ConfigBeforeHarden.ps1,
    then executes Harden-IIS.ps1 using the generated config.ini.

.PARAMETER None
    This script has no parameters — uses config.ini in current directory.

.NOTES
    - Requires Administrator rights
    - Creates timestamped backup before any changes
    - Many changes require iisreset or server restart (especially TLS/ciphers)
    - Some items require manual action (e.g. move content, add host headers)
    - Test in non-production first!
    - Use with backup/rollback scripts for safety
    - Author: Robert Weber

.EXAMPLE
    .\Harden-IIS.ps1
    Applies all enabled hardening settings from config.ini
    Performs backup → then applies hardening
#>

Write-Host "Creating backup before hardening..." -ForegroundColor Cyan
& "$PSScriptRoot\Backup-IIS-ConfigBeforeHarden.ps1"

Write-Host "`nBackup created. Starting hardening..." -ForegroundColor Green

if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
    Write-Error "This script must be run as Administrator."
    exit 1
    }

$ErrorActionPreference = "Continue"
$logFile = "Harden-IIS_$(Get-Date -Format 'yyyyMMdd-HHmmss').log"

Start-Transcript -Path $logFile -Force
    function Log {
    param([string]$Message, [string]$Level = "INFO")
        $time = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$time [$Level] $Message" | Out-Host
    }
Log "=== IIS Hardening Started ===" "INFO"

# Parse config.ini
function Get-IniContent {
param([string]$Path = "config.ini")
if (-not (Test-Path $Path)) {
        Log "ERROR: config.ini not found!" "ERROR"
exit 1
    }
    $ini = @{}
    $section = "Global"
    $ini[$section] = @{}
switch -regex -file $Path {
        "^\s*\[(.+?)\]" { $section = $matches[1].Trim(); $ini[$section] = @{} }
        "^\s*(.+?)\s*=\s*(.*)" { $name = $matches[1].Trim(); $value = $matches[2].Trim(); $ini[$section][$name] = $value }
    }
return $ini
}

try { $config = Get-IniContent } catch { Log "Failed to parse config.ini: $_" "ERROR"; exit 1 }
$globalConfig = $config["Global"]

# ===============================================
# GLOBAL HARDENING SETTINGS
# ===============================================
$globalSettings = @(
@{ Name = "DirectoryBrowsing"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/directoryBrowse" -Name "enabled" -Value $false } }
@{ Name = "SampleCodeRemoval"; Fix = { $paths = "C:\inetpub\wwwroot\iissamples","C:\Program Files\Common Files\System\msadc","C:\Program Files (x86)\Common Files\System\msadc"; foreach ($p in $paths) { if (Test-Path $p) { Remove-Item $p -Recurse -Force -ErrorAction SilentlyContinue } } } }
@{ Name = "LogAndETW"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.applicationHost/log" -Name "centralLogFileMode" -Value "CentralW3C" } }
@{ Name = "ProxyDisabled"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/proxy" -Name "enabled" -Value $false -ErrorAction SilentlyContinue } }
@{ Name = "WebDAVDisabled"; Fix = { if (Get-WindowsFeature Web-DAV-Publishing -ErrorAction SilentlyContinue) { Uninstall-WindowsFeature Web-DAV-Publishing -IncludeManagementTools } } }
# risky: @{ Name = "GlobalAuthRule"; Fix = { Remove-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/authorization" -Name "." -AtElement @{users='*';roles='';verbs=''} -ErrorAction SilentlyContinue; Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/authorization" -Name "." -Value @{accessType='Allow';roles='Administrators'} } }
@{ Name = "DeploymentRetail"; Fix = { $paths = "$env:windir\Microsoft.NET\Framework\v4.0.30319\Config\machine.config","$env:windir\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config"; foreach ($p in $paths) { if (Test-Path $p) { [xml]$xml = Get-Content $p; $node = $xml.configuration.'system.web'.deployment; if (-not $node) { $node = $xml.CreateElement("deployment"); $null = $xml.configuration.'system.web'.AppendChild($node) }; $node.SetAttribute("retail","true"); $xml.Save($p) } } } }
@{ Name = "DebugDisabled"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.web/compilation" -Name "debug" -Value $false } }
@{ Name = "XPoweredByRemoved"; Fix = { Remove-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -AtElement @{name='X-Powered-By'} -ErrorAction SilentlyContinue } }
@{ Name = "ServerHeaderRemoved"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/requestFiltering" -Name "removeServerHeader" -Value $true } }
@{ Name = "MaxAllowedContentLength"; Fix = { $val = if ($globalConfig["MaxAllowedContentLength"] -match '^\d+$') { [int]$globalConfig["MaxAllowedContentLength"] } else { 30000000 }; Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/requestFiltering/requestLimits" -Name "maxAllowedContentLength" -Value $val } }
@{ Name = "MaxUrl"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/requestFiltering/requestLimits" -Name "maxUrl" -Value 4096 } }
@{ Name = "MaxQueryString"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/requestFiltering/requestLimits" -Name "maxQueryString" -Value 2048 } }
@{ Name = "NonAsciiUrlsDisallowed"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/requestFiltering" -Name "allowHighBitCharacters" -Value $false } }
@{ Name = "DoubleEncodedRejected"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/requestFiltering" -Name "allowDoubleEscaping" -Value $false } }
@{ Name = "HttpTraceDisabled"; Fix = { Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/requestFiltering/verbs" -Name "." -Value @{verb='TRACE';allowed=$false} -ErrorAction SilentlyContinue } }
@{ Name = "UnlistedFileExtensionsDisallowed"; Fix = { $f="system.webServer/security/requestFiltering/fileExtensions"; Clear-WebConfiguration -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter $f -ErrorAction SilentlyContinue; @('.','.aspx','.ashx','.js','.css','.json','.png','.woff','.woff2','.ttf','.jpg','.svg') | ForEach-Object { Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter $f -Name "." -Value @{fileExtension=$_;allowed=$true} -ErrorAction SilentlyContinue }; Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter $f -Name "allowUnlisted" -Value $false } }
@{ Name = "HandlerNoWriteExecute"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/handlers" -Name "accessPolicy" -Value "Read,Script" } }
@{ Name = "HstsHeader"; Fix = { Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='Strict-Transport-Security';value='max-age=31536000; includeSubDomains; preload'} -ErrorAction SilentlyContinue } }
# FULL TLS/SSL REGISTRY HARDENING
@{ Name = "Sslv2Disabled"; Fix = {
foreach ($side in "Server","Client") {
            $path = "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\$side"
New-Item $path -Force | Out-Null
Set-ItemProperty $path -Name Enabled -Value 0 -Type DWord -Force
Set-ItemProperty $path -Name DisabledByDefault -Value 1 -Type DWord -Force
        }
    }}
@{ Name = "Sslv3Disabled"; Fix = {
foreach ($side in "Server","Client") {
            $path = "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\$side"
New-Item $path -Force | Out-Null
Set-ItemProperty $path -Name Enabled -Value 0 -Type DWord -Force
Set-ItemProperty $path -Name DisabledByDefault -Value 1 -Type DWord -Force
        }
    }}
@{ Name = "Tls10Disabled"; Fix = {
foreach ($side in "Server","Client") {
            $path = "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\$side"
New-Item $path -Force | Out-Null
Set-ItemProperty $path -Name Enabled -Value 0 -Type DWord -Force
Set-ItemProperty $path -Name DisabledByDefault -Value 1 -Type DWord -Force
        }
    }}
@{ Name = "Tls11Disabled"; Fix = {
foreach ($side in "Server","Client") {
            $path = "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\$side"
New-Item $path -Force | Out-Null
Set-ItemProperty $path -Name Enabled -Value 0 -Type DWord -Force
Set-ItemProperty $path -Name DisabledByDefault -Value 1 -Type DWord -Force
        }
    }}
@{ Name = "Tls12Enabled"; Fix = {
        $path = "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server"
New-Item $path -Force | Out-Null
Set-ItemProperty $path -Name Enabled -Value 1 -Type DWord -Force
Set-ItemProperty $path -Name DisabledByDefault -Value 0 -Type DWord -Force
    }}
@{ Name = "NullCipherDisabled"; Fix = {
New-Item "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL" -Force | Out-Null
Set-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\NULL" -Name Enabled -Value 0 -Type DWord -Force
    }}
@{ Name = "DesDisabled"; Fix = {
New-Item "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56/56" -Force | Out-Null
Set-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\DES 56/56" -Name Enabled -Value 0 -Type DWord -Force
    }}
@{ Name = "Rc4Disabled"; Fix = {
@('RC4 40/128','RC4 56/128','RC4 64/128','RC4 128/128') | ForEach-Object {
            $p = "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\$_"
New-Item $p -Force | Out-Null
Set-ItemProperty $p -Name Enabled -Value 0 -Type DWord -Force
        }
    }}
@{ Name = "Aes128Disabled"; Fix = {
New-Item "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128" -Force | Out-Null
Set-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 128/128" -Name Enabled -Value 0 -Type DWord -Force
    }}
@{ Name = "Aes256Enabled"; Fix = {
New-Item "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256" -Force | Out-Null
Set-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Ciphers\AES 256/256" -Name Enabled -Value 1 -Type DWord -Force
    }}
@{ Name = "TlsCipherSuiteOrdering"; Fix = {
New-Item 'HKLM:\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002' -Force | Out-Null
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Cryptography\Configuration\SSL\00010002' -Name 'Functions' -Value 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256' -Type MultiString -Force
    }}
@{ Name = "BasicAuthDisabled"; Fix = { Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/security/authentication/basicAuthentication" -Name "enabled" -Value $false } }
@{ Name = "ReferrerPolicy"; Fix = { Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='Referrer-Policy';value='strict-origin-when-cross-origin'} -ErrorAction SilentlyContinue } }
@{ Name = "XContentTypeOptions"; Fix = { Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='X-Content-Type-Options';value='nosniff'} -ErrorAction SilentlyContinue } }
@{ Name = "PermissionsPolicy"; Fix = { Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='Permissions-Policy';value='geolocation=(), microphone=(), camera=()'} -ErrorAction SilentlyContinue } }
)
# Apply Global Settings
foreach ($s in $globalSettings) {
if ($globalConfig[$s.Name] -eq "true") {
try {
& $s.Fix
            Log "SUCCESS: $($s.Name)" "SUCCESS"
        } catch {
            Log "FAILED: $($s.Name) - $_" "ERROR"
        }
    }
}
# ===============================================
# SITE-SPECIFIC HARDENING
# ===============================================
$siteSettings = @(
@{ Name = "WebContentNonSystem"; Fix = { param($site) Log "MANUAL ACTION REQUIRED: Move physical path of site '$site' to non-system drive (e.g., D:\)" "WARN" } }
@{ Name = "HostHeaders"; Fix = { param($site) $noHeader = Get-WebBinding -Name $site | Where-Object { $_.bindingInformation -match ':\d+:$' }; if ($noHeader) { Log "MANUAL: Add host header for site '$site' on bindings: $($noHeader.bindingInformation -join ', ')" "WARN" } } }
@{ Name = "AppPoolIdentity"; Fix = { param($site) $pool = (Get-Website -Name $site).applicationPool; Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.applicationHost/applicationPools/add[@name='$pool']/processModel" -Name "identityType" -Value "ApplicationPoolIdentity" } }
@{ Name = "AnonymousAppPoolIdentity"; Fix = { param($site) $pool = (Get-Website -Name $site).applicationPool; Set-ItemProperty "IIS:\AppPools\$pool" -Name processModel.passAnonymousToken -Value $true -ErrorAction SilentlyContinue; Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/security/authentication/anonymousAuthentication" -Name "userName" -Value "" } }
@{ Name = "FormsAuthRequireSSL"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.web/authentication/forms" -Name "requireSSL" -Value $true } }
@{ Name = "FormsAuthUseCookies"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.web/authentication/forms" -Name "cookieless" -Value "UseCookies" } }
@{ Name = "FormsCookieProtection"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.web/authentication/forms" -Name "protection" -Value "All" } }
@{ Name = "BasicAuthDisabled"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/security/authentication/basicAuthentication" -Name "enabled" -Value $false } }
@{ Name = "RequireSSL"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/security/access" -Name "sslFlags" -Value "Ssl" } }
@{ Name = "TraceDisabled"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.web/trace" -Name "enabled" -Value $false } }
@{ Name = "CustomErrorsNotOff"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.web/customErrors" -Name "mode" -Value "RemoteOnly" } }
@{ Name = "HttpErrorsHiddenRemote"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/httpErrors" -Name "errorMode" -Value "DetailedLocalOnly" } }
@{ Name = "SiteDirectoryBrowsing"; Fix = { param($site) Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/directoryBrowse" -Name "enabled" -Value $false } }
@{ Name = "SiteHstsHeader"; Fix = { param($site) Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='Strict-Transport-Security';value='max-age=31536000; includeSubDomains; preload'} -ErrorAction SilentlyContinue } }
@{ Name = "X-XSS-Protection"; Fix = { param($site) Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='X-XSS-Protection';value='1; mode=block'} -ErrorAction SilentlyContinue } }
@{ Name = "ContentSecurityPolicy"; Fix = { param($site) Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='Content-Security-Policy';value="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"} -ErrorAction SilentlyContinue; Log "NOTE: Basic CSP in '$site'. Customize!" "WARN" } }
@{ Name = "X-Frame-Options"; Fix = { param($site) Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='X-Frame-Options';value='SAMEORIGIN'} -ErrorAction SilentlyContinue } }
@{ Name = "ReferrerPolicy"; Fix = { param($site) Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='Referrer-Policy';value='strict-origin-when-cross-origin'} -ErrorAction SilentlyContinue } }
@{ Name = "XContentTypeOptions"; Fix = { param($site) Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='X-Content-Type-Options';value='nosniff'} -ErrorAction SilentlyContinue } }
@{ Name = "PermissionsPolicy"; Fix = { param($site) Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Location $site -Filter "system.webServer/httpProtocol/customHeaders" -Name "." -Value @{name='Permissions-Policy';value='geolocation=(), microphone=(), camera=()'} -ErrorAction SilentlyContinue } }
)
foreach ($section in $config.Keys | Where-Object { $_ -like "Site:*" }) {
    $siteName = $section.Substring(5).Trim()
if (-not (Get-Website -Name $siteName -ErrorAction SilentlyContinue)) {
        Log "Site '$siteName' not found - skipping" "WARN"
continue
    }
    Log "Processing site: $siteName" "INFO"
    $siteConfig = $config[$section]
foreach ($s in $siteSettings) {
if ($siteConfig[$s.Name] -eq "true") {
try {
& $s.Fix $siteName
                Log "SUCCESS (site $siteName): $($s.Name)" "SUCCESS"
            } catch {
                Log "FAILED (site $siteName): $($s.Name) - $_" "ERROR"
            }
        }
    }
}
Log "=== Hardening completed at $(Get-Date) ===" "INFO"
Write-Host "`nHardening finished! Full log: $logFile" -ForegroundColor Green
Write-Host "Restart the server or run 'iisreset' for TLS/cipher changes to take full effect." -ForegroundColor Yellow
Stop-Transcript