apiVersion: v2
name: zookeeper
version: 0.2.0
description: A Helm chart for Confluent Zookeeper on Kubernetes
type: application
keywords:
  - zookeeper
  - confluent
home: /helm-charts/tree/main/charts/zookeeper
sources:
  - /helm-charts
  - https://docs.confluent.io/platform/current/zookeeper/deployment.html
  - https://zookeeper.apache.org/doc/current/index.html
  - https://hub.docker.com/r/confluentinc/cp-zookeeper
maintainers:
  - name:
    email:
    url:
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/zookeeper.svg
appVersion: 7.3.0
