

[id]
name    = Splunk_TA_zeek
version = 1.0.10

[install]
is_configured = 0

[launcher]
author      = Aplura, LLC
description = The TA for Zeek allows a Splunk Enterprise administrator to parse open source Zeek data in JSON or TSV format, and map it into the Common Information Model for use by multiple Splunk security apps.
version     = 1.0.10

[package]
check_for_updates = 1
id                = Splunk_TA_zeek

[ui]
is_visible = 0
label      = Corelight Add-on for Zeek