# Server certificate CSR configuration for API Firewall
[ req ]
default_bits = 4096
prompt = no
default_md = sha512
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = US
ST = CO
L = range
O = testing
OU = wallarm
CN = api-fw

[ req_ext ]
subjectAltName = @alt_names
basicConstraints = CA:FALSE
keyUsage = critical, nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = critical, serverAuth, clientAuth

[ alt_names ]
DNS.1 = api-fw
DNS.2 = localhost