apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-ingress
  namespace: elastic
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - kibana.elastic.local
        - fleet.elastic.local
      secretName: elastic-tls
  rules:
    - host: kibana.elastic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601
    - host: fleet.elastic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleet-server
                port:
                  number: 8220