server {
    listen 80;
    server_name nessus.testing.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nessus.testing.io;

    ssl_certificate /etc/ssl/certs/nessus.testing.io.crt;
    ssl_certificate_key /etc/ssl/private/nessus.testing.io.key;
    ssl_dhparam /etc/nginx/dhparam.pem;
    include /etc/nginx/snippets/ssl-params.conf;

    location /app {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /app/index.html;
        index index.html;

        # Cache static assets
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
            expires 1y;
            access_log off;
            add_header Cache-Control "public";
        }
    }

    location /api {
        proxy_pass https://api-firewall:8088;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass https://nessus:8834;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page 404 /app/index.html;
}