apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-web
    spec:
      containers:
      - name: {{ .Chart.Name }}-web
        image: {{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}
        imagePullPolicy: {{ .Values.image.web.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: JWT_SECRET
          value: {{ .Values.jwtSecret }}
        volumeMounts:
        - name: pcaps
          mountPath: /pcaps
      volumes:
      - name: pcaps
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-pvc