apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-web
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 3000
  type: {{ .Values.service.type }}