HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Connection: close
Content-Type: application/json

{ "errors" : [ { "status" : "400", "title" : "Bad Request", "detail" : "The HTTP 400 error, also known as the Bad Request error, means that the server is unable to process a request because of an issue with the client-side. This can happen when the request is invalid, corrupted, or too large." } ] }