HTTP/1.1 504 Gateway Timeout
Cache-Control: no-cache
Connection: close
Content-Type: application/json

{ "errors" : [ { "status" : "504", "title" : "Gateway Timeout", "detail" : "The HTTP 504 error code, also known as a Gateway Timeout, indicates that a server did not receive a response in time from another server. This can happen when a server acts as a proxy or gateway." } ] }