apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  selector:
    app: flink
    component: jobmanager
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  - name: rpc
    port: 6123
    targetPort: 6123
  type: ClusterIP