volumes:
  certs:
    driver: local
  elasticsearch:
    driver: local
  kibana:
    driver: local
  fleetserver:
    driver: local

networks:
  elastic:
    driver: bridge
    ipam:
      config:
        - subnet: 10.77.0.0/16
          gateway: 10.77.0.254

x-common-vars-apps: &common-vars-apps
  security_opt:
    - no-new-privileges:true
  restart: on-failure
  env_file:
    - .env

services:
  setup:
    <<: *common-vars-apps
    profiles:
      - setup
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elastic-setup
    init: true
    volumes:
      - certs:/usr/share/elasticsearch/config/certs:z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_SYSTEM_PASSWORD} == x ]; then
          echo "Set the KIBANA_SYSTEM_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: elasticsearch\n"\
          "    dns:\n"\
          "      - elasticsearch\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: kibana\n"\
          "    dns:\n"\
          "      - kibana\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: fleet-server\n"\
          "    dns:\n"\
          "      - fleet-server\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
          cat config/certs/elasticsearch/elasticsearch.crt config/certs/ca/ca.crt > config/certs/elasticsearch/elasticsearch.chain.pem
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" https://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_SYSTEM_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/elasticsearch/elasticsearch.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
    depends_on:
      elasticsearch:
        condition: service_healthy

  coredns:
    <<: *common-vars-apps
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: coredns
    hostname: dns.containers.local
    command: -conf /etc/coredns/Corefile -dns.port 53
    ports:
      - "53:53"
      - "53:53/udp"
      - "8080:8080"
    volumes:
      - ./dns/Corefile:/etc/coredns/Corefile:ro,Z
      - ./dns/db.containers.local:/etc/coredns/db.containers.local:ro,Z
      - ./dns/db.10.77.0:/etc/coredns/db.10.77.0:ro,Z
    networks:
      elastic:
        ipv4_address: 10.77.0.2

  elasticsearch:
    <<: *common-vars-apps
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: elastic
    hostname: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
      - certs:/usr/share/elasticsearch/config/certs:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      elastic:
        ipv4_address: 10.77.0.3
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    <<: *common-vars-apps
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: kibana
    volumes:
      - certs:/usr/share/kibana/config/certs:z
      - kibana:/usr/share/kibana/data:Z
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      elastic:
        ipv4_address: 10.77.0.4
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -I -s --cacert config/certs/ca/ca.crt https://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  fleet-server:
    <<: *common-vars-apps
    build:
      context: fleet/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: fleet-server
    hostname: fleet-server
    volumes:
      - certs:/certs:z
      - fleetserver:/usr/share/elastic-agent:Z
      # stack monitoring
      - /var/lib/containers:/var/lib/docker/containers:ro
      - $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock:ro
    ports:
      - 8220:8220
    user: root
    environment:
      FLEET_ENROLL: 1
      FLEET_SERVER_POLICY_ID: fleet-server-policy
      FLEET_SERVER_ENABLE: 1
      KIBANA_FLEET_SETUP: 1
      KIBANA_HOST: https://kibana:5601
      FLEET_URL: https://fleet-server:8220
      FLEET_SERVER_ELASTICSEARCH_HOST: https://elasticsearch:9200
      FLEET_CA: /certs/ca/ca.crt
      KIBANA_FLEET_USERNAME: elastic
      KIBANA_FLEET_PASSWORD: ${ELASTIC_PASSWORD}
      FLEET_SERVER_CERT: /certs/fleet-server/fleet-server.crt
      FLEET_SERVER_CERT_KEY: /certs/fleet-server/fleet-server.key
      FLEET_SERVER_ELASTICSEARCH_CA: /certs/ca/ca.crt
      KIBANA_FLEET_CA: /certs/ca/ca.crt
    depends_on:
      kibana:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      elastic:
        ipv4_address: 10.77.0.5


