apiVersion: v2
name: ksqldb
version: 0.2.3
description: A Helm chart for Confluent ksqlDB on Kubernetes
type: application
keywords:
  - kafka
  - ksqldb
  - confluent
home: /helm-charts
sources:
  - /helm-charts
  - https://docs.confluent.io/platform/current/ksqldb/index.html
  - https://ksqldb.io
maintainers:
  - name:
    email:
    url:
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/kafka.svg
appVersion: 0.28.2
