[default]

[install]
is_configured = 0

[launcher]
description = The Sandfly Security App for Splunk includes dashboards, reports and logic for analyzing data ingested from a Sandfly Security server, including Alarms, Passed, and Errors.
version = 4.5.3
author = Sandfly Security

[package]
id = sandfly_security

[id]
name = sandfly_security
version = 4.5.3

[ui]
is_visible = 1
label = Sandfly Security

