[At_Jobs_by_Username]
dataset.type =

[Crontabs_for_All_Users]
dataset.type =

[Intrusion_Detection_High_Entropy_Process]
dataset.type =

[Intrusion_Detection_Immutable_Process_Binary_Running]
dataset.type =

[Intrusion_Detection_Process_Running_As_Sniffer]
dataset.type =

[Intrusion_Detection_Process_Running_From_devshm]
dataset.type =

[Intrusion_Detection_Process_Running_from_Public_HTML_Directory]
acceleration.hunk.dfs_block_size = 0

[Intrusion_Detection_Process_Running_From_Temp_Directory]
dataset.type =

[Logins_by_Username]
dataset.type =

[Operating_System_BIOS_Version]
dataset.type =

[Operating_System_Bogo_MIPS_Rating]
dataset.type =

[Operating_System_CPU_Architecture]
dataset.type =

[Operating_System_CPU_Model_Name]
dataset.type =

[Operating_System_Linux_Kernel_Release_Version]
dataset.type =

[Operating_System_Linux_Version]
dataset.type =

[Operating_System_Machine_Type]
dataset.type =

[Operating_System_Product_Name]
dataset.type =

[Operating_System_Uptime_in_Days]
dataset.type =

[Processes_With_Network_Ports_Listening]
dataset.type =

[Processes_With_Network_Ports_Operating]
dataset.type =

[User_Bad_Logins_Over_Time]
acceleration.hunk.dfs_block_size = 0

[User_Successful_Logins_Over_Time]
dataset.type =

[Username_Bad_Logins_by_Hostname]
dataset.type =

[Username_Logged_In]
dataset.type =

[Username_Login_Shells_In_Use]
dataset.type =

[Username_Password_Hash_Types]
dataset.type =

[Usernames_Bad_Logins_By_Username]
dataset.type =

[Usernames_Bad_Logins_From_Hostname]
dataset.type =

[Usernames_Most_Bad_Logins_Against_Hostname]
acceleration.hunk.dfs_block_size = 0

[Usernames_Present_on_Host]
dataset.type =

[Usernames_Valid_Logins_Against_Hostname]
dataset.type =

[Usernames_Valid_Logins_by_Username]
dataset.type =

[Usernames_Valid_Logins_From_Hostname]
dataset.type =

[Usernames_with_Blank_Password_Fields]
dataset.type =

[Usernames_with_Password_Hash_Present]
dataset.type =

[Usernames_with_SSH_Authorized_Keys_Present]
dataset.type =

[Usernames_Bad_Logins_Against_Hostname]
acceleration.hunk.dfs_block_size = 0

[OS_BIOS_Vendor]
acceleration.hunk.dfs_block_size = 0

[Username_root_UID_But_Not_Root]
acceleration.hunk.dfs_block_size = 0
