apiVersion: v1
kind: Service
metadata:
  name: tinyauth-service
  namespace: tinyauth
spec:
  selector:
    app: tinyauth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tinyauth-ingress
  namespace: tinyauth
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`tinyauth.example.com`)
      kind: Rule
      services:
        - name: tinyauth-service
          port: 80
    - match: Host(`whoami.example.com`)
      kind: Rule
      services:
        - name: tinyauth-service
          port: 80
      middlewares:
        - name: tinyauth-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: tinyauth-auth
  namespace: tinyauth
spec:
  forwardAuth:
    address: http://tinyauth-service.tinyauth.svc.cluster.local:3000/api/auth/traefik