<#
.SYNOPSIS
    Active Defense Daemon for Kernel C2 Beacon Hunter v3.0
    Tails the JSON monitoring log and automatically kills the process AND blocks high-confidence C2s.

    WARNING: This script will actively kill processes and block IPs if not run in -DryRun mode. Use with caution.
    Recommended to run in a separate PowerShell window while running the Full Validation Suite in another.

.EXAMPLE
    Usage:
        .\c2_defend.ps1 -LogPath "C:\Temp\C2KernelMonitoring_v3.jsonl" -ConfidenceThreshold 70
        .\c2_defend.ps1 -LogPath "C:\Temp\C2KernelMonitoring_v3.jsonl" -ConfidenceThreshold 70 -DryRun

.PARAMETER LogPath
    Path to the JSON log file generated by the monitoring script. The defender will tail this file for new alerts.
.PARAMETER ConfidenceThreshold
    Minimum confidence level (0-100) to trigger active defense actions. Adjust based on your tolerance for false positives.
.PARAMETER DryRun
    If set, the script will only print what actions it would take without actually killing processes or blocking IPs.
    Use this mode for testing and tuning before enabling active defense.

.NOTES
    Author: Robert Weber
#>

#Requires -RunAsAdministrator
param (
    [string]$LogPath = "C:\Temp\C2KernelMonitoring_v3.jsonl",
    [int]$ConfidenceThreshold = 70,
    [switch]$DryRun
)

Write-Host "[v3.0 Active Defense] Started — watching $LogPath (threshold: $ConfidenceThreshold)" -ForegroundColor Red

$lastSize = if (Test-Path $LogPath) { (Get-Item $LogPath).Length } else { 0 }

while ($true) {
    if (Test-Path $LogPath) {
        $currentSize = (Get-Item $LogPath).Length
        if ($currentSize -gt $lastSize) {
            $fs = [System.IO.File]::Open($LogPath, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
            $fs.Seek($lastSize, [System.IO.SeekOrigin]::Begin) | Out-Null
            $reader = New-Object System.IO.StreamReader($fs)
            $newContent = $reader.ReadToEnd()
            $reader.Close()
            $lastSize = $currentSize

            if (-not [string]::IsNullOrWhiteSpace($newContent)) {
                $alerts = $newContent -split "`n" | Where-Object { $_ -match "\S" } | ConvertFrom-Json -ErrorAction SilentlyContinue

                foreach ($alert in $alerts) {
                    if ($alert.Confidence -ge $ConfidenceThreshold) {

                        $dst = ($alert.Destination -split ':')[0]
                        $procPath = $alert.Image
                        $procName = if ($procPath) { [System.IO.Path]::GetFileNameWithoutExtension($procPath) } else { $null }

                        Write-Host "`n[DEFEND] C2 DETECTED (Confidence: $($alert.Confidence))" -ForegroundColor Red
                        Write-Host "    |-- Process:     $procName" -ForegroundColor Red
                        Write-Host "    |-- Destination: $dst" -ForegroundColor Red

                        if (-not $DryRun) {
                            if ($procName) {
                                Write-Host "    -> Attempting to terminate process: $procName" -ForegroundColor Yellow
                                Get-Process -Name $procName -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue

                                if (-not (Get-Process -Name $procName -ErrorAction SilentlyContinue)) {
                                    Write-Host "    -> Process terminated successfully (or already exited)." -ForegroundColor Green
                                } else {
                                    Write-Host "    -> WARNING: Failed to terminate process. It may require SYSTEM privileges." -ForegroundColor DarkYellow
                                }
                            }

                            if ($dst -match '^\d+\.\d+\.\d+\.\d+$') {
                                netsh advfirewall firewall add rule name="C2_Defend_Block_$dst" dir=out action=block remoteip=$dst protocol=any | Out-Null
                                Write-Host "    -> Firewall block added for $dst" -ForegroundColor Green
                            }
                        } else {
                            Write-Host "    [DRY-RUN] Would have killed $procName and blocked $dst" -ForegroundColor Gray
                        }
                    }
                }
            }
        }
    }
    Start-Sleep -Seconds 3
}