FROM node:22-slim AS builder
WORKDIR /app
COPY web-frontend /app
RUN npm install
RUN npm run build

FROM nginx:1.29.1-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /etc/nginx/certs /etc/letsencrypt
COPY certs/server.crt /etc/nginx/certs/server.crt
COPY certs/server.key /etc/nginx/certs/server.key
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
