apiVersion: v2
name: kafka-rest
version: 0.2.0
description: A Helm chart for Confluent Kafka REST on Kubernetes
type: application
keywords:
  - kafka
  - kafka-rest
  - confluent
home: /helm-charts
sources:
  - /helm-charts
  - https://docs.confluent.io/platform/current/kafka-rest/index.html
maintainers:
  - name:
    email:
    url:
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/kafka.svg
appVersion: 7.3.0
