# syntax=docker/dockerfile:1
# nuclei: Fast and customizable vulnerability scanner based on simple YAML based DSL.
ARG repo="docker.io" \
    base_image="alpine:3.23" \
    image_hash="25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659"

FROM ${repo}/${base_image}@sha256:${image_hash} AS go-builder

ENV GOPATH=/usr/local/bin/go \
    VER=3.4.10

RUN \
    apk add --no-cache -t .nuclei-deps \
        build-base \
        ca-certificates \
        go \
        git; \
    apk add --no-cache -t .av-scan \
        clamav \
        freshclam; \
    mkdir -p ${GOPATH}/src/github.com/nuclei; \
    cd ${GOPATH}/src/github.com/nuclei; \
    git clone --depth 1 --branch v${VER} https://github.com/projectdiscovery/nuclei; \
    cd nuclei/; \
    cd cmd/nuclei/; \
    export GO111MODULE=on; \
    go install; \
    apk del --no-network --purge .nuclei-deps; \
    freshclam; \
    clamscan -rvi -l /build_clamav_scan.log --exclude-dir="^/sys|^/dev" /; \
    grep -Hrn FOUND /build_clamav_scan.log; \
    apk del --no-network --purge .av-scan; \
    rm -rf /var/cache/apk/*; \
    rm -rf ${GOPATH}/src/

FROM ${repo}/${base_image}@sha256:${image_hash}

RUN \
    addgroup -g 65535 nuclei; \
    adduser --shell /sbin/nologin --disabled-password -h /home/nuclei --uid 65535 --ingroup nuclei nuclei; \
    apk add --no-cache \
        bash \
        bind-tools \
        ca-certificates \
        chromium

COPY --chown=nuclei:nuclei --from=go-builder /usr/local/bin/go/bin/nuclei /usr/local/bin/
COPY --chown=nuclei:nuclei --from=go-builder /build_clamav_scan.log /home/nuclei
COPY --chown=nuclei:nuclei ./custom-templates /home/nuclei/

WORKDIR /home/nuclei
USER nuclei
CMD [ "bash" ]
LABEL \
    org.opencontainers.image.name='Nuclei' \
    org.opencontainers.image.description='Fast and extensible vulnerability scanner.' \
    org.opencontainers.image.licenses='MIT' \
    org.opencontainers.image.schema-version='3.4.10'