input {
  pipeline {
    address => "beats-parse"
  }
}

filter {
  # this pipeline only needs to see logs from other misc. beats used by Malcolm
  if ("_beats" in [tags]) {
    mutate { id => "mutate_filebeat_beats_forward_tag_remove"
             remove_tag => [ "_beats" ] }
  } else {
    drop { id => "drop_not_beats" }
  }

  # rename message to event.original
  mutate { id => "mutate_rename_beats_message"
           rename => { "[message]" => "[event][original]" } }
}
