[GLOBAL]
NatsEndpoint=127.0.0.1:4222
; The persistent JetStream name that the ingress gateway writes to
TelemetryStream=SensorStream
; The specific topic/subject that the ingress gateway publishes raw telemetry to
TelemetrySubject=sensor.telemetry

[INGRESS]
; Port for the telemetry gateway
BindPort=8443
; Expected Bearer token from the sensors
AuthToken=ChangeMe
; NATS Subject for raw telemetry
TelemetrySubject=sensor.telemetry
; JetStream name for persistent storage
TelemetryStream=SensorStream

[SPLUNK]
; Splunk HEC Endpoint (Heavy Forwarder or Indexer)
HecEndpoint=https://10.0.0.50:8088/services/collector/event
HecToken=ChangeMe
; Maximum number of events to pull from NATS and push to Splunk in one HTTP request
MaxBatchSize=500
; Maximum HTTP network timeout in seconds
TimeoutSeconds=15

[ELASTIC]
; Elastic Bulk API endpoint
Endpoint=https://elastic-cluster:9200/_bulk
ApiKey=Elastic_API_Key_Here
; Maximum events per bulk push
MaxBatchSize=500