# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = false
state = enabled
build = 2

[launcher]
author = Red Hat Inc
version = 2.0.4
description = This TA enables ingestion of violation, vulnerability, and compliance data from the Red Hat Advanced Cluster Security Platform

[ui]
is_visible = 1
label = Red Hat Advanced Cluster Security
docs_section_override = AddOns:released

[package]
id = TA-stackrox

[triggers]
reload.addon_builder = simple
reload.ta_stackrox_account = simple
reload.ta_stackrox_settings = simple
reload.passwords = simple