[stackrox_compliance]
index = default
start_by_shell = false
python.version = python3
sourcetype = stackrox-compliance
interval = 14400

[stackrox_vulnerability_management]
index = default
start_by_shell = false
python.version = python3
sourcetype = stackrox-vulnmgmt
interval = 14400

[stackrox_violations]
index = default
start_by_shell = false
python.version = python3
sourcetype = stackrox-violations
interval = 60
builtin_system_checkpoint_storage_type = auto

