[stackrox-compliance]
DATETIME_CONFIG = CURRENT
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[source::...ta-stackrox*.log*]
SHOULD_LINEMERGE = true
sourcetype = tastackrox:log

[source::...ta_stackrox*.log*]
SHOULD_LINEMERGE = true
sourcetype = tastackrox:log

[stackrox-vulnmgmt]
DATETIME_CONFIG = CURRENT
EVAL-dvc = "stackrox"
EVAL-severity = case(cvss=="0", "informational", cvss>=0 AND cvss < 4, "Low", cvss >= 4.0 AND cvss < 7, "Medium", cvss >= 7 AND cvss < 9, "High", cvss >= 9, "Critical")
EVAL-signature = cve." - ".component." ".version
EVAL-url = "https://nvd.nist.gov/vuln/detail/".cve
EVAL-vendor_product = "stackrox"
FIELDALIAS-aob_gen_stackrox_vulnmgmt_alias_1 = imageDigest AS dest
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1

[stackrox-violations]
EVAL-app = "stackrox"
EVAL-dest = coalesce('deploymentInfo.clusterName' ."/". 'networkFlowInfo.destination.deploymentNamespace' . if('networkFlowInfo.destination.deploymentType'=="Pod", " > ", "/") . 'networkFlowInfo.destination.deploymentType'.":".'networkFlowInfo.destination.name', 'networkFlowInfo.destination.name')
EVAL-dest_type = coalesce('networkFlowInfo.destination.deploymentType', 'networkFlowInfo.destination.entityType')
EVAL-severity = lower(replace(replace(coalesce('policyInfo.policySeverity', "unknown"), "^UNSET_", "unknown_"), "_SEVERITY$", ""))
EVAL-src = coalesce(  'deploymentInfo.clusterName' ."/". 'networkFlowInfo.source.deploymentNamespace' . if('networkFlowInfo.source.deploymentType'=="Pod", " > ", "/") . 'networkFlowInfo.source.deploymentType'.":".'networkFlowInfo.source.name'  ,  'networkFlowInfo.source.name'  ,  'deploymentInfo.clusterName'."/".'deploymentInfo.deploymentNamespace' . if('deploymentInfo.deploymentType'=="Pod", " > ".'deploymentInfo.deploymentType'.":".'deploymentInfo.deploymentName', "/".'deploymentInfo.deploymentType'.":".'deploymentInfo.deploymentName'.coalesce(" > ".'violationInfo.podId',"")) . coalesce("/".'violationInfo.containerName',"") , 'resourceInfo.clusterName' ."/". 'resourceInfo.namespace' ."/". 'resourceInfo.resourceType' .":". 'resourceInfo.name')
EVAL-src_type = coalesce('networkFlowInfo.source.deploymentType', 'networkFlowInfo.source.entityType', 'deploymentInfo.deploymentType', 'resourceInfo.resourceType')
EVAL-type = "alert"
EVAL-user = 'processInfo.processUid'.":".'processInfo.processGid'
FIELDALIAS-aob_gen_stackrox_violations_alias_14 = violationInfo.violationId AS id
FIELDALIAS-aob_gen_stackrox_violations_alias_15 = policyInfo.policyName AS signature_id
FIELDALIAS-aob_gen_stackrox_violations_alias_16 = policyInfo.policySeverity AS vendor_severity
FIELDALIAS-aob_gen_stackrox_violations_alias_18 = violationInfo.violationMessage AS description
FIELDALIAS-aob_gen_stackrox_violations_alias_19 = policyInfo.policyDescription AS signature
KV_MODE = json
MAX_TIMESTAMP_LOOKAHEAD = 32
SHOULD_LINEMERGE = 0
TIME_PREFIX = "violationTime":\s*
category = Splunk App Add-on Builder
pulldown_type = 1

[stackrox-audit-message]
EVAL-dvc = "stackrox"
EVAL-vendor_product = "stackrox"
FIELDALIAS-aob_gen_stackrox_audit_message_alias_1 = user.role.name AS user_type
SHOULD_LINEMERGE = 0
category = Splunk App Add-on Builder
pulldown_type = 1
