
[admin:TA_stackrox]
match = /
members = TA_stackrox_settings, TA_stackrox_stackrox_compliance, TA_stackrox_stackrox_vulnerability_management, TA_stackrox_stackrox_violations

[admin_external:TA_stackrox_settings]
handlertype = python
python.version = python3
handlerfile = TA_stackrox_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_stackrox_stackrox_compliance]
handlertype = python
python.version = python3
handlerfile = TA_stackrox_rh_stackrox_compliance.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_stackrox_stackrox_vulnerability_management]
handlertype = python
python.version = python3
handlerfile = TA_stackrox_rh_stackrox_vulnerability_management.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_stackrox_stackrox_violations]
handlertype = python
python.version = python3
handlerfile = TA_stackrox_rh_stackrox_violations.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
