
[expose:TA_stackrox_settings]
pattern = TA_stackrox_settings
methods = POST, GET

[expose:TA_stackrox_settings_specified]
pattern = TA_stackrox_settings/*
methods = POST, GET, DELETE

[expose:TA_stackrox_stackrox_compliance]
pattern = TA_stackrox_stackrox_compliance
methods = POST, GET

[expose:TA_stackrox_stackrox_compliance_specified]
pattern = TA_stackrox_stackrox_compliance/*
methods = POST, GET, DELETE

[expose:TA_stackrox_stackrox_vulnerability_management]
pattern = TA_stackrox_stackrox_vulnerability_management
methods = POST, GET

[expose:TA_stackrox_stackrox_vulnerability_management_specified]
pattern = TA_stackrox_stackrox_vulnerability_management/*
methods = POST, GET, DELETE

[expose:TA_stackrox_stackrox_violations]
pattern = TA_stackrox_stackrox_violations
methods = POST, GET

[expose:TA_stackrox_stackrox_violations_specified]
pattern = TA_stackrox_stackrox_violations/*
methods = POST, GET, DELETE

[expose:_splunkd_data]
pattern = data/*
methods = GET
