#!/usr/bin/env python3
"""
api_server.py - v2.8 Metrics & Dashboard Backend (HTTPS)
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
import sqlite3
import json
import os
import glob
from pathlib import Path

app = FastAPI(title="C2 Beacon Hunter API", version="2.8")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

DB_PATH = Path("data/baseline.db")
ANOMALIES_PATH = Path("output/anomalies.jsonl")

def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

@app.get("/api/v1/metrics")
def get_metrics():
    if not DB_PATH.exists():
        return {"error": "baseline.db not found."}
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT COUNT(*) as total FROM flows")
        total_flows = cursor.fetchone()["total"]
        cursor.execute("""
            SELECT process_name, COUNT(*) as count, AVG(outbound_ratio) as avg_outbound
            FROM flows GROUP BY process_name ORDER BY count DESC LIMIT 5
        """)
        top_processes = [dict(row) for row in cursor.fetchall()]
        conn.close()
        return {"total_flows_tracked": total_flows, "top_processes": top_processes}
    except Exception as e:
        return {"error": str(e)}

@app.get("/api/v1/anomalies")
def get_recent_anomalies(limit: int = 50):
    if not ANOMALIES_PATH.exists():
        return []
    anomalies = []
    try:
        with open(ANOMALIES_PATH, "r") as f:
            lines = f.readlines()
            for line in reversed(lines[-limit:]):
                if line.strip():
                    anomalies.append(json.loads(line.strip()))
    except Exception as e:
        return {"error": str(e)}
    return anomalies

@app.get("/api/v1/threat_intel")
def get_threat_intel():
    """Fetches the most recent CTI enrichment report."""
    try:
        # Search for the reports generated by threat_intel_check.sh
        report_files = glob.glob("output/threat_intel_report_*.txt")
        if not report_files:
            return {"report": "No Threat Intel reports found. Run DFIR/threat_intel_check.sh to generate one.", "filename": None}

        # Get the newest report
        latest_report = max(report_files, key=os.path.getctime)
        with open(latest_report, "r") as f:
            content = f.read()

        return {"report": content, "filename": os.path.basename(latest_report)}
    except Exception as e:
        return {"error": str(e)}

os.makedirs("static", exist_ok=True)
app.mount("/", StaticFiles(directory="static", html=True), name="static")