apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-logs
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{storage_class}}
  resources:
    requests:
      storage: {{log_storage_size}}