[Routing]
HotDestinations=Splunk,Sentinel
ColdDestinations=Sql,Elastic
FlushBatchSize=1000
FlushIntervalMs=2000

[Splunk]
Endpoint=https://splunk.internal:8088/services/collector/event
Token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

[Elastic]
# Compatible with both ElasticSearch and OpenSearch
Endpoint=https://elastic.internal:9200/_bulk
ApiKey=Base64EncodedKey...
Index=deepsensor-ueba-events

[Sql]
ConnectionString=Server=db.internal;Database=DeepSensor;Integrated Security=True;
HotTable=TTP_Alerts
ColdTable=UEBA_Baseline

[Sentinel]
WorkspaceId=xxx
SharedKey=xxx
LogType=DeepSensor_Alerts